### ISSUE TITLE
Superagent Plugins

### ISSUE THREAD

**Issue by jamesjwarren** [jbalboni/super-res#5]
It would be nice if it were possible to additionally pass an array of superagent plugins to use with the resource. This would make customising the request simple and unlock the raft of superagent plugins available. @jbalboni what do you think? Would you accept a PR?

**Comment by jbalboni** [comment]
That sounds like a good idea to me. I am in the middle of refactoring this, though. A PR would be easier after that. I'll try to finish that today or tomorrow.

**Comment by jbalboni** [comment]
@jamesjwarren I just published my refactor, so PRs are definitely welcome. I'd like to keep the api as close to the Angular resource api as possible.

**Comment by jamesjwarren** [comment]
Nice one! Hopefully I'll get a chance to make the initial PR today.
